//from src/istrolid.js
// Generated by CoffeeScript 1.12.3
(function() {
  var dpr, globalErrors, isFirefox, keymap, updateQ,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.baseAtlas = null;

  window.intp = null;

  window.sim = null;

  window.network = null;

  window.commander = null;

  if (typeof require !== "undefined" && require !== null) {
    window.electron = require("electron");
  }

  dpr = window.devicePixelRatio;

  isFirefox = typeof InstallTrigger !== 'undefined';

  keymap = {
    38: "up",
    40: "down",
    39: "left",
    37: "right",
    33: "pageUp",
    34: "pageDown",
    87: "up",
    83: "down",
    68: "left",
    65: "right",
    69: "pageUp",
    81: "pageDown"
  };

  updateQ = [];

  globalErrors = 0;

  window.onerror = function(msg, url, line, col, e) {
    globalErrors += 1;
    if (globalErrors < 10) {
      return track("error", {
        message: msg,
        url: url,
        line: line,
        col: col,
        stack: e != null ? e.stack : void 0
      });
    }
  };

  window.Control = (function() {
    Control.prototype.jitter = 0;

    Control.prototype.perf = false;

    Control.prototype.setCursor = function(type) {
      return document.body.style.cursor = "-webkit-image-set(url('img/ui/mouses/" + type + ".png') 1x, url('img/ui/mouses/" + type + "@2x.png') 2x) 2 2, auto";
    };

    function Control() {
      this.simInterval = bind(this.simInterval, this);
      this.clearMessage = bind(this.clearMessage, this);
      this.tick = bind(this.tick, this);
      var fn1, i, len, onevent, ref;
      this.setCursor("mouse");
      this.backgroundMode = menuMode;
      this.mode = menuMode;
      this.mouse = [0, 0];
      this.observer = {};
      this.keys = {};
      ref = ["onmousemove", "ondblclick", "onmousedown", "onmouseup", "onwheel"];
      fn1 = (function(_this) {
        return function(onevent) {
          return window[onevent] = function(e) {
            var base, bounds, d, idToHide, ref1, ref2, rmenuDiv, x, y;
            if (onevent === "onmousedown") {
              if (e.target.type === "text" || e.target.type === "password" || e.target.tagName === "P") {
                return true;
              } else {
                if ((ref1 = document.activeElement) != null) {
                  if (typeof ref1.blur === "function") {
                    ref1.blur();
                  }
                }
              }
              if (ui.rmenu) {
                idToHide = ui.rmenu.id;
                after(100, function() {
                  var ref2;
                  if (idToHide === ((ref2 = ui.rmenu) != null ? ref2.id : void 0)) {
                    ui.rmenu = null;
                    return onecup.refresh();
                  }
                });
              }
              _this.mouseDown = true;
            }
            if (onevent === "onmouseup") {
              _this.mouseDown = false;
            }
            if (onevent === "onmousemove") {
              _this.mouse[0] = e.clientX;
              _this.mouse[1] = e.clientY;
              if (typeof ui !== "undefined" && ui !== null ? ui.rmenu : void 0) {
                rmenuDiv = onecup.lookup("#rmenu");
                if (rmenuDiv) {
                  bounds = rmenuDiv.getBoundingClientRect();
                  ref2 = _this.mouse, x = ref2[0], y = ref2[1];
                  d = 100;
                  if (x < bounds.left - d || x > bounds.left + bounds.width + d || y > bounds.top + bounds.height + d || y < bounds.top - d) {
                    ui.rmenu = null;
                    onecup.refresh();
                  }
                }
              }
            }
            return typeof (base = _this.mode)[onevent] === "function" ? base[onevent](e) : void 0;
          };
        };
      })(this);
      for (i = 0, len = ref.length; i < len; i++) {
        onevent = ref[i];
        fn1(onevent);
      }
      account.load();
      window.onwheel = (function(_this) {
        return function(e) {
          var base, delta;
          if (e.target.tagName === "P") {
            return;
          }
          if (isFirefox) {
            delta = e.deltaY;
          } else {
            delta = e.deltaY / 20;
          }
          return typeof (base = _this.mode).onzoom === "function" ? base.onzoom(delta, e) : void 0;
        };
      })(this);
      window.onkeydown = (function(_this) {
        return function(e) {
          var base, ref1;
          if (e.target.type === "text") {
            return;
          }
          if (e.target.type === "password") {
            return;
          }
          if (e.target.nodeName === "TEXTAREA") {
            return;
          }
          if (e.which === 8) {
            e.preventDefault();
          }
          _this.keys[e.which] = true;
          _this.keys[keymap[e.which]] = true;
          if (e.which === 13) {
            ui.chatting = true;
            setTimeout((function() {
              var ref1;
              return (ref1 = document.getElementById("chat")) != null ? ref1.focus() : void 0;
            }), 100);
            onecup.refresh();
          }
          if (settings.key(e, "Toggle UI")) {
            ui.show = !ui.show;
            onecup.refresh();
            console.log("ui hide");
          }
          if (e.which === 27) {
            control.armFullScreen = true;
          }
          if (e.shiftKey && e.which === 220) {
            control.perf = !control.perf;
            onecup.refresh();
          }
          if (settings.key(e, "Back")) {
            _this.escape();
          }
          if (e.which === 122) {
            enterFullScreen();
          }
          if (e.which === 121) {
            if (typeof electron !== "undefined" && electron !== null) {
              electron.remote.getCurrentWindow().toggleDevTools();
            }
          }
          if (e.which === 116) {
            location.reload();
          }
          if (e.which === 85) {
            if (((ref1 = window.location) != null ? ref1.href.indexOf("dev.istrolid.com") : void 0) !== -1) {
              window.testAction();
            }
          }
          return typeof (base = _this.mode).onkeydown === "function" ? base.onkeydown(e) : void 0;
        };
      })(this);
      window.onkeyup = (function(_this) {
        return function(e) {
          var base;
          if (e.which === 27 && control.armFullScreen) {
            if (typeof require === "undefined" || require === null) {
              enterFullScreen();
            }
            control.armFullScreen = false;
          }
          _this.keys[e.which] = false;
          _this.keys[keymap[e.which]] = false;
          return typeof (base = _this.mode).onkeyup === "function" ? base.onkeyup(e) : void 0;
        };
      })(this);
      window.oncontextmenu = (function(_this) {
        return function(e) {
          return false;
        };
      })(this);
    }

    Control.prototype.tick = function() {
      if (ui.mode !== ui.oldMode) {
        ui.oldMode = ui.mode;
        if (typeof rootNet !== "undefined" && rootNet !== null) {
          rootNet.sendMode();
        }
      }
      if (chat.channel !== chat.oldChannel) {
        chat.oldChannel = chat.channel;
        if (typeof rootNet !== "undefined" && rootNet !== null) {
          rootNet.sendMode();
        }
      }
      this.trySimInterval();
      actionMixer.tick();
      baseAtlas.startFrame();
      this.backgroundMode.draw();
      this.backgroundMode.tick();
      if (this.backgroundMode !== this.mode) {
        this.mode.draw();
      }
      baseAtlas.beginSprites([0, 0], 1);
      stats.fpsAdd();
      stats.draw();
      baseAtlas.finishSprites();
      this.mode.tick();
      bubbles.tick();
      tutor.tick();
      return requestAnimationFrame(this.tick);
    };

    Control.prototype.escape = function() {
      ui.mode = "battle";
      onecup.refresh();
    };

    Control.prototype.savePlayer = function() {
      account.save();
      return account.rootSave();
    };

    Control.prototype.clearMessage = function() {
      return this.message = "";
    };

    Control.prototype.lastSimInterval = 0;

    Control.prototype.cheatSimInterval = -12;

    Control.prototype.trySimInterval = function() {
      var rightNow;
      rightNow = now();
      if (this.lastSimInterval + 1000 / 16 + this.cheatSimInterval <= rightNow) {
        this.lastSimInterval = rightNow;
        return this.simInterval();
      }
    };

    Control.prototype.simInterval = function() {

      /* TODO, fix the replay system
      if intp?.playReplay
          frame = localStorage["one"].split("\n")[sim.step]
          frame = JSON.parse(frame)
          if frame?.step == 1
              sim.things = {}
              intp.things = {}
          intp.recv(frame)
          sim.step += 1
       */
      var fn, frame, galaxyAway, localAway, packet, popQ, step;
      if (typeof intp !== "undefined" && intp !== null ? intp.local : void 0) {
        packet = sim.send();
        step = sim.step;
        galaxyAway = sim.galaxyStar && ui.mode !== "battle";
        localAway = ui.mode !== "battle" && intp.state === "running";
        if (!galaxyAway && !localAway && !sim.paused) {
          sim.simulate();
        } else {
          sim.startingSim();
        }
        fn = function() {
          var data;
          stats.netAdd(packet.byteLength);
          data = intp.zJson.loadDv(packet);
          return intp.recv(data);
        };
        updateQ.unshift(fn);
        popQ = function() {
          fn = updateQ.pop();
          return fn();
        };
        setTimeout(popQ, Math.random() * control.jitter);
      }
      if ((typeof intp !== "undefined" && intp !== null ? intp.replay : void 0) === "playing") {
        frame = intp.replayFrames[intp.replayStep];
        if (frame) {
          intp.recv(frame);
          intp.replayStep += 1;
        }
      }
      if (intp) {
        return intp.think();
      }
    };

    return Control;

  })();

  window.startInitialSandbox = function() {
    var ai, aiPlayer, base, u;
    window.bubbles.clear();
    if (window.network != null) {
      if (typeof (base = window.network).close === "function") {
        base.close();
      }
    }
    window.intp = new Interpolator();
    window.sim = new Sim();
    sim.serverType = "sandbox";
    sim.local = true;
    intp.local = true;
    intp.theme = sim.theme;
    sim.start();
    window.network = new Local();
    if (onecup.params.map === "small") {
      sim.generateMap(.5, 1);
    }
    if (onecup.params.map === "medium") {
      sim.generateMap(.75, 4);
    }
    if (onecup.params.map === "super") {
      sim.generateMap(2, 8);
    }
    if (onecup.params.map === "weapontest") {
      mapping.generateWeaponTest();
      sim.victoryConditions = function() {};
    }
    if (onecup.params.speed === "fast") {
      sim.ticksPerSec = parseInt(onecup.params.speed);
      intp.ticksPerSec = sim.ticksPerSec;
      intp.fast = true;
    }
    if (onecup.params.watch === "true") {
      ais.useAi("Cython", "alpha");
      ais.useAi("AlphaSwarm", "beta");
      ais.useAi("NodeSwarm", "alpha");
      ais.useAi("Sidewinder", "beta");
      ais.useAi("CreepingHoard", "alpha");
      ais.useAi("BullDogs", "beta");
    } else if (onecup.params.evolve === "true") {
      window.evolve();
    } else if (!onecup.params.single === "true") {
      sim.ais.push(new AnarchAI("AnarchAI", "alpha"));
    } else if (onecup.params.ai != null) {
      if (ais.all[onecup.params.ai] != null) {
        ai = ais.all[onecup.params.ai];
        useAi(ai, "beta");
      } else {
        console.log("no valid ai found", onecup.params.ai);
      }
    } else if (onecup.params.boss != null) {
      aiPlayer = useAi(ais.all.BossAI, "beta");
      u = new types.Unit(fromShort(onecup.params.boss));
      u.pos = v2.create([0, 0]);
      u.side = "beta";
      u.rot = 0;
      u.owner = aiPlayer.id;
      u.number = 0;
      sim.things[u.id] = u;
    }
    window.observer = {};
    if (onecup.params.money != null) {
      sim.defaultMoney = parseInt(onecup.params.money);
    }
    actionMixer.reset();
    if (onecup.params.mapName) {
      return mapping.load(onecup.params.mapName);
    }
  };

  window.onload = function() {
    var nextMode, ref, rootAddress, ua;
    ua = detect.parse(navigator.userAgent);
    track("load", {
      electron: typeof electron !== "undefined" && electron !== null,
      path: location.pathname,
      referrer: document.referrer,
      referrer_domain: typeof document !== "undefined" && document !== null ? (ref = document.referrer.match(/https?:\/\/([^\/]*)/)) != null ? ref[1] : void 0 : void 0,
      platform: navigator.platform,
      language: navigator.language,
      browser: ua.browser.family,
      browser_version: ua.browser.version,
      device: ua.device.family,
      os: ua.os.name
    });
    if (!initGL()) {
      ui.mode = "error";
      ui.error = "webGL";
      return;
    }
    window.actionMixer = new ActionMixer();
    actionMixer.reset();
    window.battleMode = new BattleMode();
    window.galaxyMode = new GalaxyMode();
    window.designMode = new DesignMode();
    window.fleetMode = new FleetMode();
    window.menuMode = new MenuMode();
    window.control = new Control();
    window.sim = new Sim();
    window.intp = new Interpolator();
    window.baseAtlas = new Atlas();
    baseAtlas.loadAtlas(atlas);
    rootAddress = onecup.params.rootAddress || "ws://198.199.109.223:88";
    window.rootNet = new RootConnection(rootAddress);
    window.network = new Local();
    battleMode.serverToJoin = onecup.params.server;
    control.tick();
    startInitialSandbox();
    control.backgroundMode = battleMode;
    if (onecup.params.mode != null) {
      nextMode = onecup.params.mode;
      doAfter(2000, function() {
        ui.mode = nextMode;
        return onecup.refresh();
      });
    }
    return ui.loaded = true;
  };

  window.testAction = function() {
    var exp;
    console.log("here");
    exp = new types.FrameExplosion();
    exp.pos = battleMode.mouse;
    exp.rot = rand() * Math.PI * 2;
    return sim.things[exp.id] = exp;
  };

}).call(this);
;


