//from src/steam.js
// Generated by CoffeeScript 1.10.0
(function () {
    var e, error, error1, path;

    eval(onecup["import"]());

    window.steam = {};

    window.greenworks = null;

    steam.loadDLC = function () {
        if (steam.ok) {
            if (greenworks.isSubscribedApp(472490)) {
                account.DLCs['Paint Job'] = true;
                account.DLCbonus = true;
            }
            if (greenworks.isSubscribedApp(614180)) {
                account.DLCs['Curves and Shadows'] = true;
                return account.DLCbonus = true;
            }
        }
    };

    if ((typeof require !== "undefined" && require !== null) && ("" + process.argv).indexOf("no-steam") === -1) {
        print("loading green works");
        if (process.platform === 'darwin') {
            if (process.arch === 'x64') {
                path = process.execPath.replace("/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper", "");
                path += "/Contents/MacOS/lib/greenworks-osx64";
                try {
                    window.greenworks = require(path);
                } catch (error) {
                    e = error;
                    print("failed to load green works from", path, e);
                    path = process.cwd() + '/lib/greenworks-osx64';
                    try {
                        window.greenworks = require();
                    } catch (error1) {
                        e = error1;
                        print("failed to load green works from", path, e);
                    }
                }
            }
        } else if (process.platform === 'win32') {
            if (process.arch === 'x64') {
                window.greenworks = require(process.cwd() + '/lib/greenworks-win64');
            } else if (process.arch === 'ia32') {
                window.greenworks = require(process.cwd() + '/lib/greenworks-win32');
            }
        } else if (process.platform === 'linux') {
            if (process.arch === 'x64') {
                window.greenworks = require(process.cwd() + '/lib/greenworks-linux64');
            }
        }
        if (greenworks) {
            if (greenworks.initAPI()) {
                steam.ok = true;
                steam.profile = greenworks.getSteamId();
                steam.name = steam.profile.screenName;
                steam.id = steam.profile.steamId;
            } else {
                alert("Steam failed to initialize, steam features like DLC will be disabled.", "Steam API error");
                print("Could not init steam");
            }
        }
    }

}).call(this);
;


